#include <stdio.h>
#include <string.h> // Required for strlen()

// Task 09: sizeof variations
void task09() {
    printf("--- Task 09 Output ---\n");
    printf("Size of short: %zu bytes\n", sizeof(short));
    printf("Size of long: %zu bytes\n", sizeof(long));
    printf("Size of double: %zu bytes\n", sizeof(double));
    printf("Size of 'A': %zu bytes\n", sizeof('A'));
    printf("Size of \"A\": %zu bytes\n\n", sizeof("A"));
    
    /* Explanation:
       - 'A' is a character constant. In C, character constants have type 'int', 
         so sizeof('A') returns 4 (on 32/64-bit systems).
       - "A" is a string literal (an array of characters). It contains 'A' 
         and the hidden null terminator '\0', so its size is 2 bytes. */
}

// Task 10: Formatted Table
void task10() {
    printf("--- Task 10 Output ---\n");
    printf("%-10s %10s %10s\n", "Item", "Quantity", "Price");
    printf("%-10s %10d %10.2f\n", "Apples", 5, 1.50);
    printf("%-10s %10d %10.2f\n\n", "Oranges", 12, 10.75);
    
    /* Explanation:
       - The numbers (10) represent the "field width" - the minimum number 
         of characters to print. If the value is shorter, spaces are added.
       - A positive number (10) means "right-aligned" within that width.
       - A negative number (-10) means "left-aligned" within that width.
       - Example: %-10s reserves 10 spaces and puts the string on the left. */
}

// Task 11: scanf Buffer
void task11() {
    printf("--- Task 11 Output ---\n");
    int num; char ch;
    printf("Enter a number: ");
    scanf("%d", &num);
    printf("Enter a character: ");
    
    // Fix: Adding a space before %c tells scanf to skip any leading 
    // whitespace (including the newline character left in the buffer).
    scanf(" %c", &ch); 
    printf("Number: %d, Char: [%c]\n\n", num, ch);
    
    /* Explanation:
       The first scanf(%d) reads the integer but leaves the newline ('\n') 
       generated by the Enter key in the input buffer. Without the space 
       in " %c", the second scanf immediately reads that newline as the 
       character, appearing to "skip" user input. */
}

// Task 12: Debugging
void task12() {
    printf("--- Task 12 Output ---\n");
    int x; float y;
    printf("Enter an integer and a float: ");
    
    // Fix: Added '&' address-of operators and aligned specifiers.
    scanf("%d %f", &x, &y);
    
    // Fix: The product of an int and a float is a float. Printing it 
    // with %d results in a type mismatch and undefined behavior.
    printf("The product is: %.2f\n\n", x * y);
    
    /* Explanation: 
       Using %d to print a float is an error because printf expects an 
       integer bit-pattern but receives a floating-point bit-pattern. 
       The fix is to use %f to correctly interpret the floating-point result. */
}

// Task 13: Temperature conversion
void task13() {
    printf("--- Task 13 Output ---\n");
    int celsius;
    printf("Enter temp in Celsius: ");
    scanf("%d", &celsius);
    
    // Fix: Using 9.0/5.0 ensures floating-point division (1.8).
    float fahr = (celsius * 9.0 / 5.0) + 32;
    printf("%d C is %.1f F\n\n", celsius, fahr);
    
    /* Explanation:
       9/5 is integer division, which truncates the decimal and equals 1.
       9.0/5.0 is floating-point division, which equals 1.8. Using integer 
       division results in an incorrect conversion formula (F = C + 32). */
}

// Task 14: strlen vs sizeof
void task14() {
    printf("--- Task 14 Output ---\n");
    char str[50] = "Hello";
    printf("strlen(str): %zu\n", strlen(str));
    printf("sizeof(str): %zu\n\n", sizeof(str));
    
    /* Explanation:
       - strlen(str) measures the string length (number of characters) 
         excluding the null terminator. It returns 5.
       - sizeof(str) measures the total memory allocated for the array 
         in bytes. It returns 50. */
}

int main() {
    task09();
    task10();
    task11();
    task12();
    task13();
    task14();
    return 0;
}